// <auto-generated />
using System;
using FutsalAPI.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutsalAPI.Migrations
{
    [DbContext(typeof(FutsalDbContext))]
    partial class FutsalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FutsalAPI.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("FutsalAPI.modules.BookingDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("calcTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("contactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("selectCourt")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("selectDate")
                        .HasColumnType("date");

                    b.Property<string>("selectDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("selectPaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<TimeSpan>("selectTime")
                        .HasColumnType("time");

                    b.HasKey("id");

                    b.ToTable("BookingDetail");
                });

            modelBuilder.Entity("FutsalAPI.modules.FutsalDetail", b =>
                {
                    b.Property<int>("futsalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("futsalId"));

                    b.Property<string>("contactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("futsalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("operationHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("pricing")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("futsalId");

                    b.ToTable("FutsalDetail");
                });

            modelBuilder.Entity("FutsalAPI.modules.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Login");
                });
#pragma warning restore 612, 618
        }
    }
}
